# Generated by Django 2.2.4 on 2020-08-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0002_remove_dsg_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dong',
        ),
    ]
