# Generated by Django 2.2.4 on 2020-08-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0003_delete_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsg',
            name='grade',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
