# Generated by Django 2.2.4 on 2020-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0004_dsg_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsg',
            name='grade',
            field=models.CharField(default='1학년', max_length=3),
        ),
    ]
