# Generated by Django 2.2.4 on 2020-08-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0005_auto_20200820_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsg',
            name='grade',
        ),
    ]
