# Generated by Django 2.2.4 on 2020-08-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0009_dong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dong',
        ),
    ]
