# Generated by Django 2.2.4 on 2020-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0010_delete_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsg',
            name='grade',
            field=models.CharField(default='1학년', max_length=20),
        ),
    ]
