# Generated by Django 2.2.4 on 2020-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongsugong', '0013_auto_20200821_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsg',
            name='image',
            field=models.ImageField(blank=True, upload_to='dongsugong/img'),
        ),
    ]
